[build]
  command = "npm run build"
  publish = "dist/"

[[headers]]
  for = "/rss"
  [headers.values]
    Content-Type = "text/xml; charset=UTF-8"
    Content-Disposition = "inline"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/rss/"
  to = "/rss"
  status = 200

